/*
 * DIO_CFG.h
 *
 *  Created on: Aug 18, 2026
 *      Author: Abdullah
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define DIO_CNG_OUTPUT 1
#define DIO_CNG_INPUT  0

//OUTPUT
#define DIO_CNG_HIGH 1
#define DIO_CNG_LOW  0
//INPUT
#define DIO_CNG_PULLUP 1
#define DIO_CNG_FLOATING 0

// ==========================================
// PORT A: ADC & LCD Control
// ==========================================
#define PORTA_PIN0_DIRECTION DIO_CNG_INPUT  // ADC0: LM35 Temp Sensor
#define PORTA_PIN1_DIRECTION DIO_CNG_INPUT  // ADC1: Analog Humidity Sensor
#define PORTA_PIN2_DIRECTION DIO_CNG_OUTPUT // LCD RS
#define PORTA_PIN3_DIRECTION DIO_CNG_OUTPUT // LCD RW
#define PORTA_PIN4_DIRECTION DIO_CNG_OUTPUT // LCD EN
#define PORTA_PIN5_DIRECTION DIO_CNG_OUTPUT // Unused
#define PORTA_PIN6_DIRECTION DIO_CNG_OUTPUT // Unused
#define PORTA_PIN7_DIRECTION DIO_CNG_OUTPUT // Unused

// ==========================================
// PORT B: Keypad (4x4)
// ==========================================
#define PORTB_PIN0_DIRECTION DIO_CNG_OUTPUT // ROW0
#define PORTB_PIN1_DIRECTION DIO_CNG_OUTPUT // ROW1
#define PORTB_PIN2_DIRECTION DIO_CNG_OUTPUT // ROW2
#define PORTB_PIN3_DIRECTION DIO_CNG_OUTPUT // ROW3
#define PORTB_PIN4_DIRECTION DIO_CNG_INPUT  // COL0
#define PORTB_PIN5_DIRECTION DIO_CNG_INPUT  // COL1
#define PORTB_PIN6_DIRECTION DIO_CNG_INPUT  // COL2
#define PORTB_PIN7_DIRECTION DIO_CNG_INPUT  // COL3

// ==========================================
// PORT C: Hardware I2C (RTC)
// ==========================================
#define PORTC_PIN0_DIRECTION DIO_CNG_INPUT  // SCL
#define PORTC_PIN1_DIRECTION DIO_CNG_INPUT  // SDA
#define PORTC_PIN2_DIRECTION DIO_CNG_OUTPUT // Unused
#define PORTC_PIN3_DIRECTION DIO_CNG_OUTPUT // Unused
#define PORTC_PIN4_DIRECTION DIO_CNG_OUTPUT // Unused
#define PORTC_PIN5_DIRECTION DIO_CNG_OUTPUT // Unused
#define PORTC_PIN6_DIRECTION DIO_CNG_OUTPUT // Unused
#define PORTC_PIN7_DIRECTION DIO_CNG_OUTPUT // Unused

// ==========================================
// PORT D: LCD Data (8-bit)
// ==========================================
#define PORTD_PIN0_DIRECTION DIO_CNG_OUTPUT // LCD D0
#define PORTD_PIN1_DIRECTION DIO_CNG_OUTPUT // LCD D1
#define PORTD_PIN2_DIRECTION DIO_CNG_OUTPUT // LCD D2
#define PORTD_PIN3_DIRECTION DIO_CNG_OUTPUT // LCD D3
#define PORTD_PIN4_DIRECTION DIO_CNG_OUTPUT // LCD D4
#define PORTD_PIN5_DIRECTION DIO_CNG_OUTPUT // LCD D5
#define PORTD_PIN6_DIRECTION DIO_CNG_OUTPUT // LCD D6
#define PORTD_PIN7_DIRECTION DIO_CNG_OUTPUT // LCD D7


// ==========================================
// INITIAL VALUES
// ==========================================

#define PORTA_PIN0_VALUE DIO_CNG_FLOATING
#define PORTA_PIN1_VALUE DIO_CNG_FLOATING
#define PORTA_PIN2_VALUE DIO_CNG_LOW
#define PORTA_PIN3_VALUE DIO_CNG_LOW
#define PORTA_PIN4_VALUE DIO_CNG_LOW
#define PORTA_PIN5_VALUE DIO_CNG_LOW
#define PORTA_PIN6_VALUE DIO_CNG_LOW
#define PORTA_PIN7_VALUE DIO_CNG_LOW

#define PORTB_PIN0_VALUE DIO_CNG_HIGH
#define PORTB_PIN1_VALUE DIO_CNG_HIGH
#define PORTB_PIN2_VALUE DIO_CNG_HIGH
#define PORTB_PIN3_VALUE DIO_CNG_HIGH
#define PORTB_PIN4_VALUE DIO_CNG_PULLUP
#define PORTB_PIN5_VALUE DIO_CNG_PULLUP
#define PORTB_PIN6_VALUE DIO_CNG_PULLUP
#define PORTB_PIN7_VALUE DIO_CNG_PULLUP

#define PORTC_PIN0_VALUE DIO_CNG_FLOATING // I2C lines externally pulled up
#define PORTC_PIN1_VALUE DIO_CNG_FLOATING
#define PORTC_PIN2_VALUE DIO_CNG_LOW
#define PORTC_PIN3_VALUE DIO_CNG_LOW
#define PORTC_PIN4_VALUE DIO_CNG_LOW
#define PORTC_PIN5_VALUE DIO_CNG_LOW
#define PORTC_PIN6_VALUE DIO_CNG_LOW
#define PORTC_PIN7_VALUE DIO_CNG_LOW

#define PORTD_PIN0_VALUE DIO_CNG_LOW
#define PORTD_PIN1_VALUE DIO_CNG_LOW
#define PORTD_PIN2_VALUE DIO_CNG_LOW
#define PORTD_PIN3_VALUE DIO_CNG_LOW
#define PORTD_PIN4_VALUE DIO_CNG_LOW
#define PORTD_PIN5_VALUE DIO_CNG_LOW
#define PORTD_PIN6_VALUE DIO_CNG_LOW
#define PORTD_PIN7_VALUE DIO_CNG_LOW

#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
